version: "3"
services:
  prometheus44:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus22:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - sunny-service

  sunny-service:
    build: .
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus44
